### ISSUE TITLE
Not Loading PRISM.dll

### ISSUE THREAD

**Issue by WillHackett22** [PNNL-Comp-Mass-Spec/DeconTools#2]
Hello,
I just was trying to install from the 64 bit installer version on a Windows 8, 64-bit system.  I was trying to run an mzML file from ProteoWizard with the example settings; this was just to get a feel for the program. It threw an error back at me that it "Could not load file or  assembly 'PRISM, Version=2.4.4.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified."

I did not notice any errors on the install, nor on the reinstall. I also can see the PRISM version 2.4.4.0 file in the DeconTools folder. Not sure how to debug this.
Thanks!
Will

**Comment by FarmGeek4Life** [comment]
Are you seeing the PRISM dll in the .zip download files, or in the install location (that should be under C:\Program Files\DeconTools\)

I ask, because I haven't uploaded an updated installer to the omics.pnl.gov site yet, so the installer you downloaded is missing PRISM.dll, even though it exists in the contents of the downloaded .zip. Copying PRISM.dll from the .zip file to C:\Program Files\DeconTools\ is one fix for the problem.

**Comment by WillHackett22** [comment]
Oh, that was it! I copied it over and it seems to be working just fine now. Thank you!

**Comment by FarmGeek4Life** [comment]
There is an updated installer now available: https://github.com/PNNL-Comp-Mass-Spec/DeconTools/releases/latest
